### ISSUE TITLE
This extension does not seem to be working?

### ISSUE THREAD

**Issue by singularitti** [jeff-hykin/better-csv-syntax#1]
Hi, I was trying to use this extension, but it does not seem to work. I tried using other third-party themes, [XD Theme](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.xd-theme), and [Noctis](https://marketplace.visualstudio.com/items?itemName=liviuschera.noctis). None of them show any syntax highlighting of the CSV file. I tried both [Better CSV Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-csv-syntax) and [Simple CSV Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.simple-csv-syntax). Both of them show something like this:

<img width="799" alt="image" src="https://github.com/jeff-hykin/better-csv-syntax/assets/25192197/395be6ea-0a54-4f12-a72d-fb32bfb5c15f">

I also tried [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax), which does not have any apparent effect, either. However, [Better DockerFile Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-dockerfile-syntax) does improve the appearance of the code.

**Comment by jeff-hykin** [comment]
you might have to specifically select "CSV: semicolon" as the language of the file because otherwise it defaults to "CSV: commas". 

For the dockerfile syntax, are you saying iteffects CSV highlighting? Or only dockerfile highlighting

**Comment by singularitti** [comment]
> you might have to specifically select "CSV: semicolon" as the language of the fike

OK, it does work. Thanks! And BTW, should I use [Simple CSV Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.simple-csv-syntax) because it seems newer?

> For the dockerfile syntax, are you saying iteffects CSV highlighting? Or only dockerfile highlighting

Only Dockerfile, sorry for the confusion.

**Comment by jeff-hykin** [comment]
I think is also the repo for Simple CSV (I should probably un-publish "Better CSV") I just renamed it since really its not "better" just more simple.

For C++ there wont be much difference because VS Code started pre-installing the extension inside of VS Code release. Its only temporarily different when I update the extension. Same thing is true for the better shell syntax, C syntax, Obj-C, and Obj-C++.

All other syntaxes though (perl, nix, prolog, docker, etc) should be a major change fromthe default
